name: BetterTeams
main: net.lordofthecraft.betterteams.BetterTeams
description: Integrates all possible team functionality in a sensible way.
version: ${project.version}
depend: [ProtocolLib, ArcheCore]
author: Arche

commands:
  showhealth:
    description: Shows the health of each player below their name.
    permission: betterteams.showhealth
    usage: Invalid usage. Use /showhealth
    aliases: [health]
  showrpnames:
    description: Toggle between the showing of MC Names or RP names
    permission: betterteams.showrpnames
    usage: Invalid usage. Use /showrpnames
    aliases: [usernames, showusernames, showmcnames, showroleplaynames, showminecraftnames, toggleusernames, togglemcnames, mcnames, rpnames mcn, rpn]
  hidenameplates:
    description: Hide the nameplates of other players
    permission: betterteams.hidenameplates
    usage: Invalid usage. Use /hidenameplates
    aliases: [shownameplates, togglenameplates, names, nameplates, shownames, hidenames, togglenames]
  status:
    description: Update your status icon
    permission: betterteams.status
    usage: Invalid usage. For assistance, use '/status help'
  appearto:
    description: Haunt your fellow players
    permission: betterteams.appearto
    usage: Use '/appearto [player]', or '/appearto' to disappear to all.
  tagcolor:
    description: Updates the your nametag in accordance with your VIP status
    permission: betterteams.tagcolor
    usage: Invalid usage. Accepted arguments are 'on', 'off' or '[groupname]'.
    aliases: [tag]
  affixes:
    description: Shows the health of each player below their name.
    permission: betterteams.affixes
    usage: Invalid usage. Use /affixes <player>
    aliases: [aff, affix]
